/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Valerii Huhnin
-/

module

public import CompPoly.LinearAlgebra.PolynomialMatrix.Approximant.PMBasis.KernelLeafSoundness
public import CompPoly.LinearAlgebra.PolynomialMatrix.Approximant.PMBasis.KernelLeafSpan

/-!
# Kernel-Leaf Basis Generation Completeness

Every nonzero solution row of an X-adic problem lies in the row module
generated by the kernel-leaf basis: the high part is generated by the
monomial completion rows and the bounded remainder by the scalar kernel.
-/

@[expose] public section

namespace CompPoly

namespace PolynomialMatrix

namespace Approximant

variable {F : Type*} [Field F] [BEq F] [LawfulBEq F]

/-! ## Kernel-leaf basis generation completeness

Every solution row of an X-adic problem splits into a low part, whose packed
coefficient vector lies in the bounded scalar kernel, plus a high part in which
every entry is divisible by `X^(leafDegreeCap problem)`.  The low part is a
constant-coefficient combination of the reconstructed scalar-kernel rows by
`homogeneousKernelBasisRows_complete`, the high part is a polynomial
combination of the monomial completion rows, and the reduction and completion
steps only enlarge the generated row module.  Together these facts show that
the kernel-leaf basis generates every solution row. -/

section GenerationCompleteness

variable {α β : Type*}

omit [Field F] [BEq F] [LawfulBEq F] in
/-- `getD` of an array append, left side. -/
theorem pm_append_getD_left {A B : Array α} (d : α) {i : Nat}
    (hi : i < A.size) : (A ++ B).getD i d = A.getD i d := by
  rw [Array.getD_eq_getD_getElem?, Array.getD_eq_getD_getElem?,
    Array.getElem?_append_left hi]

omit [Field F] [BEq F] [LawfulBEq F] in
/-- `getD` of an array append, right side. -/
theorem pm_append_getD_right {A B : Array α} (d : α) {i : Nat}
    (hi : A.size ≤ i) : (A ++ B).getD i d = B.getD (i - A.size) d := by
  rw [Array.getD_eq_getD_getElem?, Array.getD_eq_getD_getElem?,
    Array.getElem?_append_right hi]

omit [Field F] [BEq F] [LawfulBEq F] in
private theorem pm_map_getD (f : α → β) (xs : Array α) (d : α) (e : β)
    {i : Nat} (hi : i < xs.size) :
    (xs.map f).getD i e = f (xs.getD i d) := by
  rw [array_getD_of_lt' _ _ (by simpa using hi), Array.getElem_map,
    array_getD_of_lt' _ _ hi]

end GenerationCompleteness

/-- Constant polynomial factors act coefficientwise. -/
private theorem pm_coeff_C_mul (c : F) (p : CPolynomial F) (t : Nat) :
    CPolynomial.coeff (CPolynomial.C c * p) t = c * CPolynomial.coeff p t := by
  rw [CPolynomial.coeff_toPoly, CPolynomial.toPoly_mul, CPolynomial.C_toPoly,
    Polynomial.coeff_C_mul, ← CPolynomial.coeff_toPoly]

/-- Coefficients of finite polynomial sums are coefficient sums. -/
private theorem pm_coeff_finset_sum (f : Nat → CPolynomial F) (m t : Nat) :
    CPolynomial.coeff (∑ i ∈ Finset.range m, f i) t =
      ∑ i ∈ Finset.range m, CPolynomial.coeff (f i) t := by
  rw [CPolynomial.coeff_toPoly, pm_toPoly_finset_sum, Polynomial.finsetSum_coeff]
  exact Finset.sum_congr rfl fun i _hi ↦ (CPolynomial.coeff_toPoly (f i) t).symm

/-- Coefficients of a product with the monomial `X^d`. -/
private theorem pm_coeff_mul_coeffXPower (q : CPolynomial F) (d t : Nat) :
    CPolynomial.coeff (q * coeffXPower 1 d) t =
      if d ≤ t then CPolynomial.coeff q (t - d) else 0 := by
  rw [CPolynomial.coeff_toPoly, CPolynomial.toPoly_mul, coeffXPower_toPoly,
    Polynomial.C_1, one_mul, Polynomial.coeff_mul_X_pow',
    ← CPolynomial.coeff_toPoly]

/-- A polynomial with vanishing low coefficients truncates to zero. -/
private theorem pm_truncateX_eq_zero_of_coeff (order : Nat) {p : CPolynomial F}
    (h : ∀ t, t < order → CPolynomial.coeff p t = 0) :
    truncateX order p = 0 := by
  apply CPolynomial.eq_iff_coeff.2
  intro t
  rw [truncateX_coeff, CPolynomial.coeff_zero]
  rcases Nat.lt_or_ge t order with ht | ht
  · rw [if_pos ht]
    exact h t ht
  · rw [if_neg (by omega)]

/-- A polynomial with vanishing low coefficients factors through `X^cap` with
quotient `divXTrunc cap`. -/
private theorem pm_high_factor {cap : Nat} {p : CPolynomial F}
    (hlow : ∀ t, t < cap → CPolynomial.coeff p t = 0) :
    divXTrunc cap p.val.size p * coeffXPower 1 cap = p := by
  apply CPolynomial.eq_iff_coeff.2
  intro t
  rw [pm_coeff_mul_coeffXPower]
  rcases Nat.lt_or_ge t cap with ht | ht
  · rw [if_neg (by omega), hlow t ht]
  · rw [if_pos ht, divXTrunc_coeff]
    rcases Nat.lt_or_ge (t - cap) p.val.size with hs | hs
    · rw [if_pos hs, Nat.sub_add_cancel ht]
    · rw [if_neg (by omega), CPolynomial.coeff_eq_zero_of_size_le p (by omega)]

/-- Entries of a monomial unit row. -/
theorem pm_rowGet_monomialUnitRow (n i d k : Nat) :
    rowGet (monomialUnitRow (F := F) n i d) k =
      if k < n ∧ i = k then coeffXPower 1 d else 0 := by
  rcases Nat.lt_or_ge k n with hk | hk
  · rw [monomialUnitRow, rowGet, Array.getD_eq_getD_getElem?,
      List.getElem?_toArray, List.getElem?_map, List.getElem?_range hk,
      Option.map_some, Option.getD_some]
    by_cases hik : i = k
    · rw [if_pos (beq_iff_eq.mpr hik), if_pos ⟨hk, hik⟩]
    · rw [if_neg (by simpa using hik), if_neg fun h ↦ hik h.2]
  · rw [monomialUnitRow, rowGet, Array.getD_eq_getD_getElem?,
      List.getElem?_toArray, List.getElem?_eq_none (by simpa using hk),
      Option.getD_none, if_neg fun h ↦ absurd h.1 (Nat.not_lt.mpr hk)]

/-- The completion matrix has one row per module coordinate. -/
private theorem pm_completionRows_size (problem : XAdicProblem F) :
    (kernelLeafCompletionRows problem).size = problem.matrix.size := by
  simp [kernelLeafCompletionRows]

/-- In-range rows of the completion matrix are monomial unit rows. -/
private theorem pm_completionRows_getD (problem : XAdicProblem F) {i : Nat}
    (hi : i < problem.matrix.size) :
    (kernelLeafCompletionRows problem).getD i #[] =
      monomialUnitRow problem.matrix.size i (leafDegreeCap problem) := by
  simp only [kernelLeafCompletionRows]
  rw [Array.getD_eq_getD_getElem?, List.getElem?_toArray, List.getElem?_map,
    List.getElem?_range hi, Option.map_some, Option.getD_some]

/-- Entries of a row linear combination are coefficient-weighted entry sums. -/
theorem pm_rowGet_rowLinearCombination (coeffs : Array (CPolynomial F))
    (M : PolynomialMatrix F) (j : Nat) :
    rowGet (rowLinearCombination coeffs M) j =
      ∑ i ∈ Finset.range M.size, coeffs.getD i 0 * rowGet (M.getD i #[]) j := by
  rw [rowLinearCombination]
  have hfold : ∀ m : Nat,
      rowGet ((List.range m).foldl
        (fun acc i ↦ rowAdd acc
          (rowScalePolynomial (coeffs.getD i 0) (M.getD i #[])))
        (zeroRow (MatrixWidth M))) j =
      ∑ i ∈ Finset.range m, coeffs.getD i 0 * rowGet (M.getD i #[]) j := by
    intro m
    induction m with
    | zero => simp [rowGet_zeroRow]
    | succ m ih =>
        rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil,
          rowGet_rowAdd, ih, rowGet_rowScalePolynomial, Finset.sum_range_succ]
  exact hfold M.size

/-- Row linear combinations of uniform-width matrices keep that width. -/
theorem pm_rowLinearCombination_size {M : PolynomialMatrix F} {n : Nat}
    (hsizes : ∀ r ∈ MatrixRows M, r.size = n) (hw : MatrixWidth M = n)
    (coeffs : Array (CPolynomial F)) :
    (rowLinearCombination coeffs M).size = n := by
  rw [rowLinearCombination]
  have hfold : ∀ m : Nat, m ≤ M.size →
      ((List.range m).foldl
        (fun acc i ↦ rowAdd acc
          (rowScalePolynomial (coeffs.getD i 0) (M.getD i #[])))
        (zeroRow (MatrixWidth M))).size = n := by
    intro m
    induction m with
    | zero =>
        intro _
        simp [zeroRow, hw]
    | succ m ih =>
        intro hm
        rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil,
          rowAdd_size, ih (by omega), rowScalePolynomial_size,
          hsizes _ (getD_mem_matrixRows (by omega)), Nat.max_self]
  exact hfold M.size (Nat.le_refl _)

omit [BEq F] [LawfulBEq F] in
/-- Rows agreeing in size and on every `rowGet` entry are equal. -/
theorem pm_row_ext {a b : PolynomialRow F} (hsize : a.size = b.size)
    (h : ∀ j, rowGet a j = rowGet b j) : a = b := by
  refine Array.ext hsize fun j hj hj' ↦ ?_
  have hget := h j
  rw [rowGet, rowGet, array_getD_of_lt' _ _ hj, array_getD_of_lt' _ _ hj']
    at hget
  exact hget

/-- Rows whose entries are all divisible by `X^(leafDegreeCap problem)` satisfy
every X-adic condition. -/
private theorem pm_rowApproximates_of_entry_dvd (mulCtx : CPolynomial.MulContext F)
    (problem : XAdicProblem F) {row : PolynomialRow F}
    (h : ∀ k, (Polynomial.X : Polynomial F) ^ leafDegreeCap problem ∣
      (rowGet row k).toPoly) :
    RowApproximates mulCtx problem row := by
  rw [rowApproximates_iff]
  intro j hj _hjw
  refine Finset.dvd_sum fun k _hk ↦ ?_
  refine Dvd.dvd.mul_right (dvd_trans (pow_dvd_pow _ ?_) (h k)) _
  exact le_trans (getD_le_maxOrder problem hj) (Nat.le_max_right 1 _)

/-- All kernel-leaf input rows have the principal row width. -/
private theorem pm_kernelLeafUnion_sizes (problem : XAdicProblem F) :
    ∀ r ∈ MatrixRows
      ((homogeneousKernelBasisRows (coefficientMatrixRows problem)
          (problem.matrix.size * leafDegreeCap problem)).map
        (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
        kernelLeafCompletionRows problem),
      r.size = problem.matrix.size := by
  intro r hr
  rw [MatrixRows, Array.toList_append] at hr
  rcases List.mem_append.mp hr with hr | hr
  · rw [Array.toList_map] at hr
    rcases List.mem_map.mp hr with ⟨w, _hw, rfl⟩
    simp [vectorToPolynomialRow]
  · simp only [kernelLeafCompletionRows] at hr
    rcases List.mem_map.mp hr with ⟨i, _hi, rfl⟩
    simp [monomialUnitRow]

/-- **Low part.**  A bounded solution row, all of whose entry coefficients live
below the leaf degree cap, lies in the row span of the kernel-leaf input rows:
its packed coefficient vector is orthogonal to the scalar coefficient matrix,
so scalar-kernel completeness reconstructs it as a constant-coefficient
combination of the reconstructed kernel rows. -/
private theorem pm_lowRow_mem_rowSpan_union (mulCtx : CPolynomial.MulContext F)
    (problem : XAdicProblem F) (hpos : 0 < problem.matrix.size)
    (hwf : WellFormed problem.matrix) {rem : PolynomialRow F}
    (happrox : RowApproximates mulCtx problem rem)
    (hsize : rem.size = problem.matrix.size)
    (hdeg : ∀ k, k < rem.size → ∀ a, leafDegreeCap problem ≤ a →
      CPolynomial.coeff (rowGet rem k) a = 0) :
    rem ∈ RowSpan
      ((homogeneousKernelBasisRows (coefficientMatrixRows problem)
          (problem.matrix.size * leafDegreeCap problem)).map
        (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
        kernelLeafCompletionRows problem) := by
  have hcap_pos : 0 < leafDegreeCap problem := le_max_left 1 _
  have hrt := vectorToPolynomialRow_rowToCoefficientVector problem hsize hdeg
  have hdot := coefficientMatrixRows_dot_eq_zero_of_approximates mulCtx problem
    happrox hwf
  have hcomplete := homogeneousKernelBasisRows_complete
    (coefficientMatrixRows problem)
    (problem.matrix.size * leafDegreeCap problem) hdot
  set cols := problem.matrix.size * leafDegreeCap problem with hcols
  set kb := homogeneousKernelBasisRows (coefficientMatrixRows problem) cols
    with hkbdef
  set free := DenseMatrix.freeColumns cols
    (scalarRrefRows (coefficientMatrixRows problem) cols).pivots with hfreedef
  set v := rowToCoefficientVector problem rem with hvdef
  set M := kb.map
      (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
    kernelLeafCompletionRows problem with hMdef
  have hMsizes : ∀ r ∈ MatrixRows M, r.size = problem.matrix.size := by
    rw [hMdef, hkbdef, hcols]
    exact pm_kernelLeafUnion_sizes problem
  have hMsize : M.size = kb.size + problem.matrix.size := by
    rw [hMdef, Array.size_append, Array.size_map, pm_completionRows_size]
  have hMpos : 0 < M.size := by omega
  have hMwidth : MatrixWidth M = problem.matrix.size :=
    matrixWidth_eq_of_first_row hMpos hMsizes
  set coeffs : Array (CPolynomial F) := Array.ofFn (fun i : Fin M.size ↦
      if i.val < kb.size then CPolynomial.C (v.getD (free.getD i.val 0) 0)
      else 0)
    with hcoeffsdef
  have hcoeffs_getD : ∀ x, x < M.size →
      coeffs.getD x 0 =
        if x < kb.size then CPolynomial.C (v.getD (free.getD x 0) 0)
        else 0 := by
    intro x hx
    rw [hcoeffsdef, array_getD_of_lt' _ _ (by simpa using hx)]
    simp
  refine ⟨coeffs, by rw [hcoeffsdef]; simp, ?_⟩
  refine pm_row_ext
    (by rw [hsize, pm_rowLinearCombination_size hMsizes hMwidth]) ?_
  intro j
  rw [pm_rowGet_rowLinearCombination]
  apply CPolynomial.eq_iff_coeff.2
  intro a
  rw [pm_coeff_finset_sum]
  have hsub : Finset.range kb.size ⊆ Finset.range M.size := by
    intro x hx
    rw [Finset.mem_range] at hx ⊢
    omega
  have hvan : ∀ x ∈ Finset.range M.size, x ∉ Finset.range kb.size →
      CPolynomial.coeff (coeffs.getD x 0 * rowGet (M.getD x #[]) j) a = 0 := by
    intro x hx hxn
    have hxM : x < M.size := Finset.mem_range.mp hx
    have hxkb : kb.size ≤ x := by
      rcases Nat.lt_or_ge x kb.size with h | h
      · exact absurd (Finset.mem_range.mpr h) hxn
      · exact h
    rw [hcoeffs_getD x hxM, if_neg (by omega), zero_mul,
      CPolynomial.coeff_zero]
  refine Eq.trans ?_ (Finset.sum_subset hsub hvan)
  have hterm : ∀ i ∈ Finset.range kb.size,
      CPolynomial.coeff (coeffs.getD i 0 * rowGet (M.getD i #[]) j) a =
        v.getD (free.getD i 0) 0 *
          (if j < problem.matrix.size ∧ a < leafDegreeCap problem then
            (kb.getD i #[]).getD (j * leafDegreeCap problem + a) 0
          else 0) := by
    intro i hi
    have hikb : i < kb.size := Finset.mem_range.mp hi
    have hiM : i < M.size := by omega
    have hMget : M.getD i #[] =
        vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size
          (kb.getD i #[]) := by
      rw [hMdef, pm_append_getD_left _ (by rw [Array.size_map]; exact hikb),
        pm_map_getD _ _ #[] _ hikb]
    rw [hcoeffs_getD i hiM, if_pos hikb, hMget, pm_coeff_C_mul,
      rowGet_vectorToPolynomialRow_coeff]
  have hlhs : CPolynomial.coeff (rowGet rem j) a =
      if j < problem.matrix.size ∧ a < leafDegreeCap problem then
        v.getD (j * leafDegreeCap problem + a) 0
      else 0 := by
    rw [← hrt, rowGet_vectorToPolynomialRow_coeff]
  rw [hlhs, Finset.sum_congr rfl hterm]
  by_cases hcond : j < problem.matrix.size ∧ a < leafDegreeCap problem
  · rw [if_pos hcond]
    obtain ⟨hidx, -, -⟩ := pm_pack_index hcap_pos hcond.1 hcond.2
    refine Eq.trans (hcomplete _ (by rw [hcols]; exact hidx)) ?_
    exact Finset.sum_congr rfl fun i _hi ↦ by rw [if_pos hcond]
  · rw [if_neg hcond]
    exact (Finset.sum_eq_zero fun i _hi ↦ by rw [if_neg hcond, mul_zero]).symm

/-- **High part.**  A row whose entry coefficients all vanish below the leaf
degree cap lies in the row span of the kernel-leaf input rows: every entry
factors through `X^(leafDegreeCap problem)`, so the row is a polynomial
combination of the monomial completion rows. -/
private theorem pm_highRow_mem_rowSpan_union (problem : XAdicProblem F)
    (hpos : 0 < problem.matrix.size) {hi : PolynomialRow F}
    (hsize : hi.size = problem.matrix.size)
    (hlow : ∀ k a, a < leafDegreeCap problem →
      CPolynomial.coeff (rowGet hi k) a = 0) :
    hi ∈ RowSpan
      ((homogeneousKernelBasisRows (coefficientMatrixRows problem)
          (problem.matrix.size * leafDegreeCap problem)).map
        (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
        kernelLeafCompletionRows problem) := by
  set A := (homogeneousKernelBasisRows (coefficientMatrixRows problem)
      (problem.matrix.size * leafDegreeCap problem)).map
    (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size)
    with hAdef
  set M := A ++ kernelLeafCompletionRows problem with hMdef
  have hMsizes : ∀ r ∈ MatrixRows M, r.size = problem.matrix.size := by
    rw [hMdef, hAdef]
    exact pm_kernelLeafUnion_sizes problem
  have hMsize : M.size = A.size + problem.matrix.size := by
    rw [hMdef, Array.size_append, pm_completionRows_size]
  have hMpos : 0 < M.size := by omega
  have hMwidth : MatrixWidth M = problem.matrix.size :=
    matrixWidth_eq_of_first_row hMpos hMsizes
  have hMget_right : ∀ {b : Nat}, A.size ≤ b → b < M.size →
      M.getD b #[] =
        monomialUnitRow problem.matrix.size (b - A.size)
          (leafDegreeCap problem) := by
    intro b hb hbM
    rw [hMdef, pm_append_getD_right _ hb,
      pm_completionRows_getD problem (by omega)]
  set coeffs : Array (CPolynomial F) := Array.ofFn (fun i : Fin M.size ↦
      if A.size ≤ i.val then
        divXTrunc (leafDegreeCap problem)
          ((rowGet hi (i.val - A.size)).val.size) (rowGet hi (i.val - A.size))
      else 0)
    with hcoeffsdef
  have hcoeffs_getD : ∀ x, x < M.size →
      coeffs.getD x 0 =
        if A.size ≤ x then
          divXTrunc (leafDegreeCap problem)
            ((rowGet hi (x - A.size)).val.size) (rowGet hi (x - A.size))
        else 0 := by
    intro x hx
    rw [hcoeffsdef, array_getD_of_lt' _ _ (by simpa using hx)]
    simp
  refine ⟨coeffs, by rw [hcoeffsdef]; simp, ?_⟩
  refine pm_row_ext
    (by rw [hsize, pm_rowLinearCombination_size hMsizes hMwidth]) ?_
  intro j
  rw [pm_rowGet_rowLinearCombination]
  by_cases hj : j < problem.matrix.size
  · have hother : ∀ b ∈ Finset.range M.size, b ≠ A.size + j →
        coeffs.getD b 0 * rowGet (M.getD b #[]) j = 0 := by
      intro b hb hbne
      have hbM : b < M.size := Finset.mem_range.mp hb
      rcases Nat.lt_or_ge b A.size with hbA | hbA
      · rw [hcoeffs_getD b hbM, if_neg (by omega), zero_mul]
      · rw [hMget_right hbA hbM, pm_rowGet_monomialUnitRow,
          if_neg (by rintro ⟨-, h2⟩; exact hbne (by omega)), mul_zero]
    refine (Eq.trans (Finset.sum_eq_single_of_mem (A.size + j)
      (Finset.mem_range.mpr (by omega)) hother) ?_).symm
    rw [hcoeffs_getD _ (by omega), if_pos (Nat.le_add_right _ _),
      hMget_right (Nat.le_add_right _ _) (by omega), Nat.add_sub_cancel_left,
      pm_rowGet_monomialUnitRow, if_pos ⟨hj, rfl⟩]
    exact pm_high_factor fun t ht ↦ hlow j t ht
  · have hzero : rowGet hi j = 0 := by
      rw [rowGet, array_getD_of_le' _ _ (by omega)]
    rw [hzero]
    refine (Finset.sum_eq_zero fun b hb ↦ ?_).symm
    have hbM : b < M.size := Finset.mem_range.mp hb
    rcases Nat.lt_or_ge b A.size with hbA | hbA
    · rw [hcoeffs_getD b hbM, if_neg (by omega), zero_mul]
    · rw [hMget_right hbA hbM, pm_rowGet_monomialUnitRow,
        if_neg fun h ↦ hj h.1, mul_zero]

/-- **Decomposition.**  Every solution row splits as a truncated low part plus
an `X^(leafDegreeCap)`-divisible high part, both of which stay in the row span
of the kernel-leaf input rows. -/
private theorem pm_solution_mem_rowSpan_union (mulCtx : CPolynomial.MulContext F)
    (problem : XAdicProblem F) (hpos : 0 < problem.matrix.size)
    (hwf : WellFormed problem.matrix) {row : PolynomialRow F}
    (happrox : RowApproximates mulCtx problem row)
    (hsize : row.size = problem.matrix.size) :
    row ∈ RowSpan
      ((homogeneousKernelBasisRows (coefficientMatrixRows problem)
          (problem.matrix.size * leafDegreeCap problem)).map
        (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
        kernelLeafCompletionRows problem) := by
  set hi : PolynomialRow F := Array.ofFn (fun k : Fin row.size ↦
      rowGet row k.val -
        truncateX (leafDegreeCap problem) (rowGet row k.val))
    with hhidef
  have hhisize : hi.size = row.size := by
    rw [hhidef]
    simp
  have hhiget : ∀ k, rowGet hi k =
      rowGet row k - truncateX (leafDegreeCap problem) (rowGet row k) := by
    intro k
    rcases Nat.lt_or_ge k row.size with hk | hk
    · rw [rowGet, array_getD_of_lt' _ _ (by omega)]
      simp only [hhidef, Array.getElem_ofFn]
    · rw [rowGet, array_getD_of_le' _ _ (by omega), rowGet,
        array_getD_of_le' _ _ hk, truncateX_zero_eq_zero, sub_zero]
  have hhilow : ∀ k a, a < leafDegreeCap problem →
      CPolynomial.coeff (rowGet hi k) a = 0 := by
    intro k a ha
    rw [hhiget k, CPolynomial.coeff_sub, truncateX_coeff, if_pos ha, sub_self]
  have hhiapprox : RowApproximates mulCtx problem hi := by
    refine pm_rowApproximates_of_entry_dvd mulCtx problem fun k ↦ ?_
    rw [← truncateX_eq_zero_iff_X_pow_dvd]
    exact pm_truncateX_eq_zero_of_coeff _ fun t ht ↦ hhilow k t ht
  have hremget : ∀ k, rowGet (rowSub row hi) k =
      truncateX (leafDegreeCap problem) (rowGet row k) := by
    intro k
    rw [rowGet_rowSub, hhiget k, sub_sub_cancel]
  have hremsize : (rowSub row hi).size = problem.matrix.size := by
    rw [rowSub_size, hhisize, Nat.max_self, hsize]
  have hremdeg : ∀ k, k < (rowSub row hi).size → ∀ a,
      leafDegreeCap problem ≤ a →
      CPolynomial.coeff (rowGet (rowSub row hi) k) a = 0 := by
    intro k _hk a ha
    rw [hremget k, truncateX_coeff, if_neg (by omega)]
  have hremapprox : RowApproximates mulCtx problem (rowSub row hi) :=
    rowApproximates_rowSub mulCtx problem happrox hhiapprox
  have hsplit : rowAdd (rowSub row hi) hi = row := rowSub_add_cancel hhisize
  rw [← hsplit]
  exact rowAdd_mem_rowSpan
    (pm_lowRow_mem_rowSpan_union mulCtx problem hpos hwf hremapprox hremsize
      hremdeg)
    (pm_highRow_mem_rowSpan_union problem hpos (hhisize.trans hsize) hhilow)

/-- The incremental kernel-leaf reduction keeps a uniform input row width. -/
private theorem pm_reduceIncremental_sizes {n : Nat}
    {rows : PolynomialMatrix F} (shift : Array Nat)
    (hsizes : ∀ r ∈ MatrixRows rows, r.size = n) :
    ∀ r ∈ MatrixRows (reduceKernelLeafRowsIncremental rows shift),
      r.size = n := by
  intro r hr
  refine reduceKernelLeafRowsIncremental_invariant (fun row ↦ row.size = n)
    ?_ shift hsizes hr
  intro target reducer shift' ht hrd
  rw [cancelKernelLeafLeadingTerm]
  split
  · split
    · split
      · exact ht
      · rw [rowSub_size, rowScaleCoeffX_size]
        omega
    · exact ht
  · exact ht

/-- **Generation completeness of the kernel-leaf basis.**  Every nonzero
solution row of an X-adic problem lies in the row module generated by the
kernel-leaf basis. -/
theorem kernelLeafBasis_rowSpan_complete [DecidableEq F]
    (mulCtx : CPolynomial.MulContext F) (problem : XAdicProblem F)
    (shift : Array Nat) (hpos : 0 < problem.matrix.size)
    (hwf : WellFormed problem.matrix) {row : PolynomialRow F}
    (happrox : RowApproximates mulCtx problem row)
    (hsize : row.size = problem.matrix.size)
    (_hnz : ¬ RowIsZero row) :
    row ∈ RowSpan (kernelLeafBasis problem shift) := by
  have hrow_union := pm_solution_mem_rowSpan_union mulCtx problem hpos hwf
    happrox hsize
  set union := (homogeneousKernelBasisRows (coefficientMatrixRows problem)
      (problem.matrix.size * leafDegreeCap problem)).map
    (vectorToPolynomialRow (leafDegreeCap problem) problem.matrix.size) ++
    kernelLeafCompletionRows problem with hunion
  set reduced := reduceKernelLeafRowsIncremental union shift with hreduced
  have hbasis_eq : kernelLeafBasis problem shift =
      reduced ++ missingCompletionRows problem shift reduced := by
    rw [hreduced, hunion]
    simp only [kernelLeafBasis, completeMissingPivotRows]
  have hunionsizes : ∀ r ∈ MatrixRows union, r.size = problem.matrix.size := by
    rw [hunion]
    exact pm_kernelLeafUnion_sizes problem
  have hredsizes : ∀ r ∈ MatrixRows reduced, r.size = problem.matrix.size := by
    rw [hreduced]
    exact pm_reduceIncremental_sizes shift hunionsizes
  have hwit_mem : monomialUnitRow (F := F) problem.matrix.size 0
      (leafDegreeCap problem) ∈ MatrixRows union := by
    rw [hunion, MatrixRows, Array.toList_append]
    refine List.mem_append.mpr (Or.inr ?_)
    simp only [kernelLeafCompletionRows]
    exact List.mem_map.mpr ⟨0, List.mem_range.mpr hpos, rfl⟩
  have hwit_size : (monomialUnitRow (F := F) problem.matrix.size 0
      (leafDegreeCap problem)).size = problem.matrix.size := by
    simp [monomialUnitRow]
  have hwit_nz : ¬ RowIsZero (monomialUnitRow (F := F) problem.matrix.size 0
      (leafDegreeCap problem)) := by
    intro hz
    have hget : rowGet (monomialUnitRow (F := F) problem.matrix.size 0
        (leafDegreeCap problem)) 0 = coeffXPower 1 (leafDegreeCap problem) := by
      rw [pm_rowGet_monomialUnitRow, if_pos ⟨hpos, rfl⟩]
    have hmem0 : (monomialUnitRow (F := F) problem.matrix.size 0
        (leafDegreeCap problem))[0]'(by omega) ∈
        (monomialUnitRow (F := F) problem.matrix.size 0
          (leafDegreeCap problem)).toList :=
      Array.getElem_mem_toList (by omega)
    have hzero := hz _ hmem0
    rw [rowGet, array_getD_of_lt' _ _ (by omega), hzero] at hget
    have hone : CPolynomial.coeff (coeffXPower (1 : F) (leafDegreeCap problem))
        (leafDegreeCap problem) = 1 := by
      rw [CPolynomial.coeff_toPoly, coeffXPower_toPoly, Polynomial.coeff_C_mul,
        Polynomial.coeff_X_pow, if_pos rfl, mul_one]
    rw [← hget, CPolynomial.coeff_zero] at hone
    exact zero_ne_one hone
  have hwit_span : monomialUnitRow (F := F) problem.matrix.size 0
      (leafDegreeCap problem) ∈ RowSpan reduced := by
    rw [hreduced]
    exact reduceKernelLeafRowsIncremental_rowSpan_superset hunionsizes
      hwit_mem hwit_nz
  have hredpos : 0 < reduced.size := by
    rcases Nat.eq_zero_or_pos reduced.size with h0 | hp
    · exfalso
      rw [Array.eq_empty_of_size_eq_zero h0] at hwit_span
      have hweq := eq_empty_of_mem_rowSpan_empty hwit_span
      rw [hweq] at hwit_size
      simp at hwit_size
      omega
    · exact hp
  have hunionpos : 0 < union.size := by
    rw [hunion, Array.size_append, pm_completionRows_size]
    omega
  have hunionwidth : MatrixWidth union = problem.matrix.size :=
    matrixWidth_eq_of_first_row hunionpos hunionsizes
  have hredwidth : MatrixWidth reduced = problem.matrix.size :=
    matrixWidth_eq_of_first_row hredpos hredsizes
  have hsub1 : RowSpan union ⊆ RowSpan reduced := by
    refine rowSpan_subset_of_rows_mem (wellFormed_of_sizes hredsizes)
      (hunionwidth.trans hredwidth.symm) ?_
    intro r hr
    by_cases hz : RowIsZero r
    · have hreq : r = zeroRow problem.matrix.size := by
        have hzr := rowIsZero_eq_zeroRow hz
        rwa [hunionsizes r hr] at hzr
      rw [hreq]
      have hzero := zeroRow_mem_rowSpan (wellFormed_of_sizes hredsizes)
      rwa [hredwidth] at hzero
    · rw [hreduced]
      exact reduceKernelLeafRowsIncremental_rowSpan_superset hunionsizes hr hz
  have hbasissizes : ∀ r ∈ MatrixRows (kernelLeafBasis problem shift),
      r.size = problem.matrix.size :=
    fun r hr ↦ (kernelLeafBasis_rows mulCtx problem shift r hr).2
  have hbasispos : 0 < (kernelLeafBasis problem shift).size := by
    rw [hbasis_eq, Array.size_append]
    omega
  have hbasiswidth : MatrixWidth (kernelLeafBasis problem shift) =
      problem.matrix.size :=
    matrixWidth_eq_of_first_row hbasispos hbasissizes
  have hsub2 : RowSpan reduced ⊆ RowSpan (kernelLeafBasis problem shift) := by
    refine rowSpan_subset_of_rows_mem (wellFormed_of_sizes hbasissizes)
      (hredwidth.trans hbasiswidth.symm) ?_
    intro r hr
    refine matrix_row_mem_rowSpan (wellFormed_of_sizes hbasissizes) ?_
    rw [hbasis_eq, MatrixRows, Array.toList_append]
    exact List.mem_append.mpr (Or.inl hr)
  exact hsub2 (hsub1 hrow_union)

end Approximant

end PolynomialMatrix

end CompPoly
